services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Vancado\VncNews\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Vancado\VncNews\Command\ImportWpNewsCommand:
    tags:
      -
        name: console.command
        command: 'vnc-news:import-wp-news'
        description: 'Imports WordPress WXR (XML)'
        schedulable: true
  Vancado\VncNews\LinkHandler\NewsImageLinkHandler:
    public: true
    # The link handler keeps a state and can therefore be no singleton
    shared: false
